version: 0.2

env:
  parameter-store:
    key1: "google_ad_client"
    key2: "googleAnalytics"
    key3: "CloudFrontDistributionID"
phases:
  build:
    commands:
      - echo $key1 >> ./test/test.txt
      - echo $key2 >> ./test/test.txt
  post_build:
    commands:
      - aws s3 sync --exact-timestamps --delete test/ s3://www.yokochi.jp/test
      - aws cloudfront create-invalidation --distribution-id $key3 --paths "/sorry/*"
