version: 0.2

env:
  parameter-store:
    key: "google_ad_client"
phases:
  build:
    commands:
      - echo $key >> ./test/test.txt
  post_build:
    commands:
      - aws s3 sync --exact-timestamps --delete test/ s3://www.yokochi.jp/test
