version: 0.2

env:
  parameter-store:
    key1: "google_ad_client"
    key2: "googleAnalytics"
    key3: "CloudFrontDistributionID"
#    key4: "rakuten_motion_widget"
#    key5: "amazon_Mobile_Popover"
phases:
  install:
    commands:
      - curl -Ls https://github.com/gohugoio/hugo/releases/download/v0.46/hugo_0.46_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
      - tar xf /tmp/hugo.tar.gz -C /tmp
      - mv /tmp/hugo /usr/bin/hugo
      - rm -rf /tmp/hugo*
  build:
    commands:
#      - echo $key5 >> ./themes/nederburg/layouts/partials/head.html
      - echo $key1 >> ./themes/nederburg/layouts/partials/header.html
#      - echo $key4 >> ./themes/nederburg/layouts/partials/footer.html
      - echo $key2 >> ./config.toml
      - cat ./config-add.toml >> config.toml
      - cat ./config.toml
      - hugo     
  post_build:
    commands:
      - aws s3 sync --exact-timestamps --delete public/ s3://www.yokochi.jp
      - aws cloudfront create-invalidation --distribution-id $key3 --paths "/*"
