baseurl = "https://www.yokochi.jp/"
title = "shigeru-yokochi"
theme = "nederburg"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-121444026-1"
preserveTaxonomyNames = true
paginate = 10 #frontpage pagination

[params]
  slogan = "A fast &amp; secure site"
  description = "Describe your website" # meta description
  author = "Shigeru Yokochi"
  authorLink = "https://www.yokochi.jp/"

#  bio = [ "お問い合わせはこちらへxxxxxxx"  ]
  copyright = [ "&copy; 2018 yokochi.jp",    "",    ""  ]


#  bio = [
#    "Goran is an avid blogger and the founder of <a href='https://www.yokochi.jp/'>Appernetic.io</a>. This is the author bio shown after posts."
#  ]
#  copyright = [
#    "&copy; 2018 Goran Svensson",
#    "Nederburg Hugo Theme by [Appernetic](https://appernetic.io).",
#    "A port of Tracks by Compete Themes."
#  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "shigeru@yokochi.jp"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

#  [[menu.main]]
#  name = "About"
#  url = "about/"
#  weight = 2

#  [[menu.main]]
#  name = "Get in touch"
#  url = "contact/"
#  weight = 3

[[menu.main]]
  name = "raspberrypi"
  url = "/categories/raspberrypi"
  weight = 80


[[menu.main]]
  name = "drone"
  url = "/categories/drone"
  weight = 90

[[menu.main]]
  name = "trekking"
  url = "/categories/trekking"
  weight = 100


[[menu.main]]
  name = "bike"
  url = "/categories/bike"
  weight = 150




  [params.social]
  facebook      = "https://www.facebook.com/shigeru.yokochi"
  googleplus    = "full profile url in googleplus"
  email         = "shigeru@yokochi.jp"
  twitter       = "full profile url in twitter"
  linkedin      = "full profile url in linkedin"
  stackoverflow = "full profile url in stackoverflow"
  instagram     = "https://www.instagram.com/shigeru_yokochi_01/"
  github        = "https://github.com/shigeru-yokochi"
  pinterest     = "full profile url in pinterest"
  rss           = true




