[params]
  slogan = "A fast &amp; secure site"
  description = "Describe your website" # meta description
  author = "Shigeru Yokochi"
  authorLink = "https://www.yokochi.jp/"
#  bio = [ "お問い合わせはこちらへxxxxxxx"  ]
  copyright = [ "&copy; 2018 yokochi.jp",    "",    ""  ]
  email = "shigeru@yokochi.jp"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1


[[menu.main]]
  name = "raspberrypi"
  url = "/categories/raspberrypi"
  weight = 80

[[menu.main]]
  name = "IT"
  url = "/categories/IT"
  weight = 85


[[menu.main]]
  name = "drone"
  url = "/categories/drone"
  weight = 90

[[menu.main]]
  name = "trekking"
  url = "/categories/trekking"
  weight = 100

[[menu.main]]
  name = "camp"
  url = "/categories/camp"
  weight = 101

[[menu.main]]
  name = "camera"
  url = "/categories/camera"
  weight = 101

[[menu.main]]
  name = "bike"
  url = "/categories/bike"
  weight = 150

[[menu.main]]
  name = "audio"
  url = "/categories/audio"
  weight = 160

[[menu.main]]
  name = "About me"
  url = "/categories/About-me"
  weight = 300


[params.social]
  facebook      = "https://www.facebook.com/shigeru.yokochi"
  googleplus    = "full profile url in googleplus"
  email         = "shigeru@yokochi.jp"
  twitter       = "full profile url in twitter"
  linkedin      = "full profile url in linkedin"
  stackoverflow = "full profile url in stackoverflow"
  instagram     = "https://www.instagram.com/shigeru_yokochi_01/"
  github        = "https://github.com/shigeru-yokochi"
  pinterest     = "full profile url in pinterest"
  rss           = true

